
name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    environment: production
    runs-on: self-hosted
    steps:
      - name: Deploy in EC2
        uses: appleboy/ssh-action@v0.1.10
        env:
          PATH_REPO: "/data/repo/leaderboard"
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            pwd
            ls -al /data
            cd /data/repo/leaderboard
            ls -al
            git checkout ${{ github.head_ref || github.ref_name }}
            git fetch --all
            git reset --hard origin/${{ github.head_ref || github.ref_name }}
            git pull origin ${{ github.head_ref || github.ref_name }}
            npm install --force --production
            pm2 start ecosystem.config.js --env production
