
name: Node.js CI

on:
  push:
    branches: [ "main" ]

env:
  PATH_REPO: "/data/repo/leaderboard"

jobs:
  build:
    environment: production
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd $PATH_REPO &&
            git checkout ${{ github.head_ref || github.ref_name }} &&
            git fetch --all &&
            git reset --hard origin/${{ github.head_ref || github.ref_name }} &&
            git pull origin ${{ github.head_ref || github.ref_name }} &&
            npm install --force --production &&
            pm2 start ecosystem.config.js --env production
          '
