
name: Node.js CI

on:
  push:
    branches: [ "main" ]

env:
  PATH_REPO: "/data/repo/leaderboard"

jobs:
  build:
    environment: production
    runs-on: self-hosted
    steps:
      - name: Deploy in EC2
        uses: appleboy/ssh-action@v0.1.10
        env:
          PATH_REPO: "PATH_REPO"
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            ls -al
            pwd
            cd $PATH_REPO
            ls -al
            git checkout ${{ github.head_ref || github.ref_name }}
